flask/flask/project_tasks/modular_app/tasks/models.py
"""Este arcivo 'models.py' funciona para registrar todos los modelos (tablas) de la bd, 
   que esten relacionados con las tareas o tasks, asi comunicarnos con la bd.

   FACILITA LA MIGRACION DE LA APP YA QUE NO SE NECESITA DE UN ARCHIVO EXTERNO
   POR EL CONTROL QUE SE REALIZA MEDIANTE SQLALCHEMY A LA RESPECTIVA BD"""

from modular_app import oDb
from sqlalchemy.orm import relationship #relacion entre tablas de la BD

#Pivot tables
#Esta tabla mostrara los muchos ID de task asociados a lo muchos ID de tag
task_tags = oDb.Table('pivot_tasks_tags',
                      oDb.Column('task_id', oDb.Integer, oDb.ForeignKey('tasks.id')),
                      oDb.Column('tag_id', oDb.Integer, oDb.ForeignKey('tasks_tags.id'))
                     )




#Models
"""Clase task (modelo base de datos). Tabla flask_tasks 
   Este se entiende como la clase task (tabla de la bd task)"""
class Task(oDb.Model):
    __tablename__ = 'tasks'
    
    #Fields
    id = oDb.Column(oDb.Integer, primary_key=True)
    name = oDb.Column(oDb.String(255))
    document_id = oDb.Column(oDb.Integer, oDb.ForeignKey('tasks_documents.id'), nullable=True)
    category_id = oDb.Column(oDb.Integer, oDb.ForeignKey('tasks_categories.id'), nullable=True)

    #Relationship
    """Relacion entre task y document (1 tarea puede contener 1 documento)
    por lo que document tendra el documento relacionado con el ID de la task consultada
    esto es igual a: document = oDb.session.query(models.Documents).get(document_id) 
    esta funcion en la ruta de update en el modelo task"""

    document = relationship('Documents', lazy='joined')
    category = relationship('Category', lazy='joined')
    tags = relationship(argument='Tag', secondary=task_tags)

"""Clase Category (Categorias de las TASK)
    Como no se creara un modulo de CRUD para las categories por ello se crean en el mismo archivo
    de modelos (tablas de base de datos) de TASK"""
class Category(oDb.Model):
    #Una Categoria puede estar en MUCHAS tareas
    __tablename__ = "tasks_categories"

    #Fields
    id = oDb.Column(oDb.Integer, primary_key=True)
    name = oDb.Column(oDb.String(100))

"""Clase Tag(tags de las tareas)"""
class Tag(oDb.Model):
    #MUCHOS tag pueden estar en MUCHAS tareas
    __tablename__="tasks_tags"

    #Fields
    id = oDb.Column(oDb.Integer, primary_key=True)
    name = oDb.Column(oDb.String(100))

flask/flask/project_tasks/modular_app/tasks/forms.py
"""Flask-WTF Esta lib facilita la integracion de forms y el server, debido a que permite controlar los forms 
    directamente con backend"""

from flask_wtf import FlaskForm
from wtforms import StringField, FileField, SelectField, HiddenField
from wtforms.validators import InputRequired

#Clase de formulario para task
class TaskForm(FlaskForm):
    name = StringField(label='Name', validators=[InputRequired()])
    file = FileField(label='Document',) #optional
    category = SelectField(label='Category', validators=[InputRequired()])

class TaskAddTagForm(FlaskForm):
    tag = SelectField(label='Tag',)

class TaskDeleteTagForm(FlaskForm):
    tag = HiddenField(label='Tag',)

flask/flask/project_tasks/modular_app/tasks/controllers.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, flash, session

from flask_login import login_required

from modular_app.tasks import models, sql_operations, forms
from modular_app.documents import sql_operations as doc_sql_operations

from modular_app import app
from modular_app import config

from werkzeug.utils import secure_filename

taskRoute = Blueprint('tasks', __name__, url_prefix='/tasks')

@taskRoute.before_request
@login_required
def before():
    pass

@taskRoute.route('/')
def index():
    #tasks = sql_operations.getAllTask()
    page = request.args.get(key='page', default=1, type=int)        
    tasks = sql_operations.pagination(page=page, count=10)

    return render_template('dashboard/task/index.html', tasks = tasks)

@taskRoute.route('/create', methods=['POST', 'GET'])
def create():
    frm = forms.TaskForm()

    #Agrego opciones a el elemento SELECT
    frm.category.choices = [(row.id, row.name) for row in models.Category.query.all()]

    if frm.validate_on_submit():
        sql_operations.createTask(frm.name.data, frm.category.data)

        return redirect(url_for('tasks.index'))
        #print(request.args.get('task'))

    return render_template('dashboard/task/create.html', form=frm)

@taskRoute.route('/update/<int:id>', methods=['POST', 'GET'])
def update(id:int):
    oTask = sql_operations.getTaskById(id)
    
    frm = forms.TaskForm()    
    frm.category.choices = [(row.id, row.name)for row in models.Category.query.all()]
    frm.category.data = str(oTask.category.id)

    #Tags
    #Add
    frmTag = forms.TaskAddTagForm()
    frmTag.tag.choices = [(row.id, row.name)for row in models.Tag.query.all()]
    #Remove
    frmTagRem = forms.TaskDeleteTagForm()

    if request.method == 'GET':        
        frm.name.data = oTask.name
    elif request.method == 'POST':
        if frm.validate_on_submit():            
            #Valida archivo cargado
            oFileStorage = frm.file.data

            if oFileStorage and config.validate_ext_file(filename=oFileStorage.filename):
                fileName = secure_filename(oFileStorage.filename)
                oFileStorage.save(os.path.join(app.config['UPLOAD_FOLDER'], fileName))

                oDocument = doc_sql_operations.createDocument(filename=fileName)
                #actualiza task con el respectivo id del document creado
                sql_operations.updateTask(taskId=id, taskName=frm.name.data, documentId=oDocument.id, categoryID=oTask.category.id)

                flash(message='Registro actualizado correctamente') 

            #return redirect(url_for('tasks.index'))
    
    return render_template('dashboard/task/update.html', form=frm, frmTag=frmTag, frmTagRem=frmTagRem,id=oTask.id, task=oTask)

@taskRoute.route('/delete/<int:id>', methods=['GET'])
def delete(id:int):
    oTask = sql_operations.getTaskById(id)
    
    sql_operations.deleteTask(taskId=oTask.id)

    if oTask.document_id is not None:
        doc_sql_operations.deleteDocument(oTask.document_id)
    
        filename = oTask.document.name
        os.remove(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    return redirect(url_for('tasks.index'))

#Tag
@taskRoute.route('/<int:id>/tag/add', methods=['POST'])
def addTag(id:int):
    formTag = forms.TaskAddTagForm()
    formTag.tag.choices = [(row.id, row.name)for row in models.Tag.query.all()]

    if(formTag.validate_on_submit()):
        sql_operations.addTagTask(taskId=id, tagId=formTag.tag.data)

    return redirect(url_for('tasks.update', id=id))

@taskRoute.route('/<int:id>/tag/remove', methods=['POST'])
def deleteTag(id:int):
    frmTagRem = forms.TaskDeleteTagForm()
    tagId = frmTagRem.tag.data

    if(frmTagRem.validate_on_submit()):
        sql_operations.removeTagTask(taskId=id, tagId=tagId)

    return redirect(url_for('tasks.update', id=id))

flask/flask/project_tasks/modular_app/templates/dashboard/task/create.html
{% extends "dashboard/master.html" %}

{% block title %} Create {% endblock %}

{% block content %}
   <form action="" method="post">
      {% include 'dashboard/task/form.html' %}
   </form>
{% endblock %}

flask/flask/project_tasks/modular_app/templates/dashboard/task/form.html
<div class="row">
   <div class="col">
      {{form.name.label(class="form-label")}}
      {{form.name(class="form-control")}}
      {% if form.name.errors %}
         {% for error in form.name.errors %}
            <p>{{error}}</p>
         {% endfor %}
      {% endif %}
   </div>
   <div class="col">
      {{form.category.label(class="form-label")}}
      {{form.category(class="form-select")}}
      {% if form.category.errors %}
         {% for error in form.category.errors %}
            <p>{{error}}</p>
         {% endfor %}
      {% endif %}
   </div>
   {% if id: %}
      <div class="col">
         {{form.file.label(class="form-label")}}
         {{form.file(class="form-control")}}
      </div>
   {% endif %}
</div>

<!--Valido errores
{% if form.errors %}
    {% for error in form.errors %}
        <script>
        alert("{{error}}")
        </script>
    {% endfor %}
{% endif %}-->

{{form.csrf_token}}
<button class="btn btn-success btn-md my-2" type="submit">Send</button>

flask/flask/project_tasks/modular_app/templates/dashboard/task/index.html
{% extends "dashboard/master.html" %}
{% from "macro/pagination.html" import m_pagination %}

{% block title %} Index task {% endblock %}

{% block content %}
   <a class="btn btn-success btn-sm" href="{{url_for('tasks.create')}}">Create task</a>
   <table class="table">
      <thead>
         <tr>
            <th>Tarea</th>
            <th>Categoria</th>
            <th>Edita</th>
            <th>Borra</th>
         </tr>
      </thead>
      {% for task in tasks.items %}
         <tbody>
         <tr>
         <td>{{task.name}}</td>
         <td>{{task.category.name}}</td>
         <td><a class="btn btn-secondary btn-sm" href="{{url_for('tasks.update', id=task.id)}}">Edita</a></td>
         <td><a class="btn btn-danger btn-sm" href="{{url_for('tasks.delete', id=task.id)}}">Borra</a></td> 
         </tr>
         </tbody>
      {% endfor %}
   </table>
   
   {{m_pagination(dataPag=tasks)}}
{% endblock %}

flask/flask/project_tasks/modular_app/templates/dashboard/task/update.html
{% extends "dashboard/master.html" %}

{% block title %} Update {% endblock %}

{% block content %}
   {% include 'dashboard/utils/messages.html' %}

   <form action="" method="post" enctype="multipart/form-data">
      {% include 'dashboard/task/form.html'%}
   </form>

   {% if task.document: %}
      <div class="row">
         <div class="col col-sm-2">
            <h4>Documento:</h4>
         </div>
         <div class="col">
            {% with document=task.document%}
               {% include 'dashboard/documents/detail.html' %}
            {% endwith %}
         </div>
      </div>
   {% endif %}

   <div class="mt-2">
      <h4>Etiquetas</h4>
      {% include 'dashboard/task/tags/index.html' %}
   </div>

   {% include 'dashboard/task/tags/assign.html' %}
{% endblock %}